### ISSUE TITLE
undefined method `full_gem_path' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#149]
In order to deliver the linux binary we are 'wrapping' it into snap package

After migration to tebako I see the issue:

```
/__tebako_memfs__/local/metanorma:154:in `<main>': undefined method `full_gem_path' for nil:NilClass (NoMethodError)
Error: Process completed with exit code 1.
```

@maxirmx any idea why this may happens?

**Comment by maxirmx** [comment]
Disclaimer.  I am not Ruby expert.

The line 154 (that was created prior to tebako) 
```
sevenz_path = File.join(Gem.loaded_specs['seven_zip_ruby'].full_gem_path, 'lib', 'seven_zip_ruby', sevenz_lib)
```
always looked like a mistery for me since it was executed before explicit or implicit _require 'seven_zip_ruby'_
I was not able to make it work in any code other then metanorma wheather I packaged it with tebako or called unpackaged

In my much simplified test for this gem I am using:
```
sevenz_path = File.join(Gem::Specification.find_by_name("seven_zip_ruby").full_gem_path, 'lib', 'seven_zip_ruby', sevenz_lib)
```
https://github.com/tamatebako/tebako/blob/main/tests-2/fixtures/gems-seven_zip_ruby/gems-seven_zip_ruby.rb
This is the only suggestion I have.

**Comment by CAMOBAP** [comment]
Thanks, hmm interesting why it doesn't fail on CI for this repo...
I will check if the issue reproduced without Gemfile in CWD
