### ISSUE TITLE
Update packed-mn release for Windows with libmspack test files removed in ruby-libmspack

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#155]
This has now been merged: https://github.com/davispuh/ruby-libmspack/issues/2#issuecomment-1040625023

We want to re-release on Windows for a new Chocolatey package that does not trigger virus warnings:
https://github.com/metanorma/chocolatey-metanorma/issues/69

**Comment by CAMOBAP** [comment]
Released today https://github.com/metanorma/packed-mn/actions/runs/2026985237

I will keep this open till get virus report

**Comment by CAMOBAP** [comment]
Well, report changes +1 issue, so the total is 9 now, unfortunately, I cannot get more details from the virus scan https://www.virustotal.com/graph/61b6b6c08372af64a5a2b19a9bbb5413e7f22db418e34e9e3d422a8350fd8a68 because of my account restriction.

Most issues stay the same so I asked chocolatey admins to approve it manually

**Comment by CAMOBAP** [comment]
Last package was approved, so I closing this one, but for long term I will still think how we can research such issues in the future
