### ISSUE TITLE
Add Alpine linux build for packed-mn

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#158]
I suppose we will need to update Tebako to support this?

**Comment by maxirmx** [comment]
We will have to create build scripts for everything
folly 
dwarfs
libdwarfs
tebako-patched ruby

There are some known issues with folly (ref https://github.com/facebook/folly/issues/1478)  This is something to start with.

**Comment by ronaldtse** [comment]
For Ruby, this is how the Docker team compiles Ruby on Alpine: https://github.com/docker-library/ruby/blob/master/3.1/alpine3.15/Dockerfile

**Comment by maxirmx** [comment]
Well, they have broken ncurses package
![image](https://user-images.githubusercontent.com/2081498/161399583-33c428f0-4db0-4b21-8172-0ff5096e5031.png)

static library is missing though the link is there. This is not a showstopper, but another package to build and install manually

**Comment by ronaldtse** [comment]
> Well, they have broken ncurses package ![image](https://user-images.githubusercontent.com/2081498/161399583-33c428f0-4db0-4b21-8172-0ff5096e5031.png)
> 
> static library is missing though the link is there. This is not a showstopper, but another package to build and install manually

Is this a bug with Alpine? If so, we probably should report to Alpine?

**Comment by maxirmx** [comment]
> Is this a bug with Alpine? If so, we probably should report to Alpine?

Prior to v3.15 there is no ncurses static library at all
In 3.15 there is a bug as shown
In the latest edge (unstable) it is fixed, so I do not think we need to report.
I  consider it too risky to use to unstable version.

**Comment by ronaldtse** [comment]
Got it, then we should make packed-mn available for Alpine > 3.15, ignoring 3.15.

**Comment by maxirmx** [comment]
https://github.com/facebook/folly/issues/1754

**Comment by maxirmx** [comment]
Alpine 3.16 (which is now 'latest') installs gcc 11.x that does not work for seven_zip_ruby      
https://github.com/masamitsu-murase/seven_zip_ruby/issues/36

**Comment by maxirmx** [comment]
**Status**
I have created a preliminary version of Alpine CI script 

- seven_zip_ruby compatibility issue  Alpine 3.16 (which is now 'latest') installs gcc 11.x that does not work for seven_zip_ruby https://github.com/masamitsu-murase/seven_zip_ruby/issues/36
I am dealing with it by building on Alpine 3.15  but it can be considered short term solution obly

- expressir musl compatibility issue https://github.com/lutaml/expressir/issues/106
I am dealing with it by using ```force_ruby_platform true```  but it has side effect of rebuilding extensions for other gems and causes the next issue

- when native extensions for  nokogiry and some other gems are rebuild they use dynamic linking and create external dependancies that need to be satisfied at run time: ```apk --no-cache --upgrade add git libstdc++ xz libarchive```   
I am ignoring it for now though these requirements violate initial self-sufficiency requirement

- fontist gem has some ssl certificates issue
```/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/fontist-1.14.2/lib/fontist/font_installer.rb:68:in `download_file': Invalid URL: https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip. Error: #<Down::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>. (Fontist::Errors::InvalidResourceError)```
openssl does verification without problems and wget works with this uri so it is not about missing certificate.
This issue is blocker for now. Probably we need to create Alpine CI for fontis as well

Attn @ronaldtse
