### ISSUE TITLE
Tebako setup CMake Error at CMakeLists.txt:700 for macos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#184]
- https://github.com/metanorma/packed-mn/actions/runs/3736221022/jobs/6348024330#step:9:3837

```
CMake Error at CMakeLists.txt:700 (target_link_libraries):
-- Generating done
  Target "dwarfs" links to:

    PkgConfig::LIBARCHIVE

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by maxirmx** [comment]
It is homebrew issue:
https://github.com/libarchive/libarchive/issues/1819
https://github.com/mpv-player/mpv/issues/11012

**Comment by maxirmx** [comment]
UPD
libarchive 3.6.2 has packaging [bug](https://github.com/libarchive/libarchive/issues/1819) 
homebrew blindly updated their libarchive formula to 3.6.2 with no options to install any other version

The solution would be to eliminate either pkg-config or homebrew or both for libarchive setup on MacOS. It is doable but will require some time since it needs to be implemented through all projects (dwarfs, libdwarfs, tebako, packed-mn)
