### ISSUE TITLE
Can we compile metanorma binary with static pthreads

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#194]
### Intro

During linuxbrew CI crashes research I noted a this one:

> /home/linuxbrew/.linuxbrew/Cellar/metanorma/1.6.12_1/bin/metanorma-linux-x86_64: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /home/linuxbrew/.linuxbrew/Cellar/metanorma/1.6.12_1/bin/metanorma-linux-x86_64

### Question

Is `temtebako` allow us to link `glib` and `pthreads` statically to our metanorma binary to avoid such problems?

**Comment by maxirmx** [comment]
No. Not glibc, pthread and dl  if we have native extensions that are shared libraries
The reason:
Pls have a look at the diagram https://github.com/tamatebako/tebako/issues/42#issuecomment-1018498412

Arrows "1" and "3" shall point to the same module (for glibc, pthread and dl)  otherwise it crashes
