### ISSUE TITLE
Ensure Java programs like plantuml and mn2pdf are properly run inside the single binary

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#38]
As title.

**Comment by CAMOBAP** [comment]
I suppose the check already done on https://github.com/metanorma/mn2pdf-ruby/blob/master/lib/mn2pdf.rb#L28

And because we are running tests on different flavors metanorma will be finished with error exit code if one of the output failed

Regarding plantuml, we use it as an external dependency there should not be a problem when it exists, but I'm not sure that plantuml involved in the current test scenarios (correct me if I'm wrong)

@ronaldtse maybe you can suggest how we can test plantuml integration by calling metanorma?

**Comment by ronaldtse** [comment]
> I suppose the check already done on https://github.com/metanorma/mn2pdf-ruby/blob/master/lib/mn2pdf.rb#L28

Not really -- the packed-mn environment is very different because the JAR and associated files are located in the enclosed FS but need to interact with the user files on local FS. Moreover, mn2pdf needs to load fonts from ~/.metanorma/fonts, which is on local FS.

From my conversion with @w00lf it seems that mn2pdf etc will NOT work currently due to the way the enclosed FS is used.

A possible workaround is to copy out executable files (JAR + any necessary files from the enclosed FS, e.g. XLS or schema files) to a temporary directory on local FS, and execute them there.

We need to test to find out whether the PDFs are currently generated properly. @CAMOBAP can you help on this? Thanks.

**Comment by CAMOBAP** [comment]
> @CAMOBAP can you help on this?

Yep, I saw calls to mn2pdf.jar in tests and it looks like it works properly, let me doublecheck

**Comment by ronaldtse** [comment]
We also use mn2sts.

In total, we use these JARs:

* plantuml
* Jing
* mn2pdf
* mn2sts

Hope we can resolve this very soon. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse #49 ready for review
