### ISSUE TITLE
(URGENT) Packed-mn auto-release failure??

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#65]
@CAMOBAP a new metanorma-cli has been released but it did not trigger a build here?

<img width="715" alt="image" src="https://user-images.githubusercontent.com/11865/92984071-250edb80-f4da-11ea-9f0e-fa33377d23ee.png">

**Comment by CAMOBAP** [comment]
I think it may be related to test failure https://github.com/metanorma/metanorma-cli/runs/1102347518?check_suite_focus=true because we trigger dispatch_repository on `ruby = 2.6` for version v1.3.7.2

But release happens for  v1.3.7.3 because tests for `ruby = 2.6` passed successfully 

<img width="828" alt="Screen Shot 2020-09-12 at 7 16 39 AM" src="https://user-images.githubusercontent.com/2169738/92987076-eb34d980-f4c7-11ea-9bc3-c0188578719c.png">

As a solution, I see the only option to move it to a separate workflow, but in this case, it will not depend on tests

@ronaldtse how do you think?

**Comment by CAMOBAP** [comment]
release process will be improved in scope of https://github.com/metanorma/metanorma-cli/issues/174
