### ISSUE TITLE
Reference auto-fetching doesn't work yet

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#9]
With packed-mn on macOS:

```sh
~/Downloads/metanorma-darwin-x64.dms sources/iso-rice-en.adoc 
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
fetching ISO 3696...
Could not retrieve ISO 3696: no access to online site
fetching ISO 5725-1...
Could not retrieve ISO 5725-1: no access to online site
fetching ISO 5725-2...
Could not retrieve ISO 5725-2: no access to online site
fetching ISO 6322-1...
Could not retrieve ISO 6322-1: no access to online site
fetching ISO 6322-2...
Could not retrieve ISO 6322-2: no access to online site
fetching ISO 6322-3...
Could not retrieve ISO 6322-3: no access to online site
fetching ISO 7301...
Could not retrieve ISO 7301: no access to online site
fetching ISO 14864...
Could not retrieve ISO 14864: no access to online site
fetching IEC 61010-2...
Could not retrieve IEC 61010-2: no access to online site
ISO style: WARNING (Line 61): Foreword may contain requirement: ISO shall not be held responsible for identifying any or all such patent rights
ISO style: WARNING (Line 61): Foreword may contain permission: Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights
```

With normal macOS:
```sh
bundle exec metanorma sources/iso-rice-en.adoc 
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
fetching ISO 712...
fetching ISO 6646...
fetching ISO 8351-1...
fetching ISO 8351-2...
fetching ISO 20483...
fetching ISO 24333...
fetching ISO 3696...
...
```

**Comment by w00lf** [comment]
This particular error happens because of ssl certificate verification failure during https request to https://www.iso.org:

![image](https://user-images.githubusercontent.com/1158036/67163702-dc5aab00-f37a-11e9-8006-11ea01c46891.png)

Gem relaton_iso is fixed on https request to www.iso.org:
https://github.com/relaton/relaton-iso/blob/v0.6.5/lib/relaton_iso/hit_collection.rb#L24

Verification fails because of compilation packing specific OpenSSL version into binary:
![image](https://user-images.githubusercontent.com/1158036/67163918-a539c900-f37d-11e9-817f-166fabebaa25.png)

As such certificates is not included into binary. The workaround now will be to completely disable ssl verification(dirty hack) or investigate further how binary can lookup system certificates, this will take longer time to implement.

**Comment by ronaldtse** [comment]
@w00lf Questions:

1. If we bundle the OS SSL certificates, will it work?
2. We probably should update the OpenSSL version? 2017 is a LONG time ago...

**Comment by ronaldtse** [comment]
And in general we should probably update all the Ruby-packer vendor dependencies to the latest released versions.

**Comment by w00lf** [comment]
>1. If we bundle the OS SSL certificates, will it work?

I think it will, you can set cert file for openssl gem inside the code. The question here is how much time we will spend on this in the end) 

> 2. We probably should update the OpenSSL version? 2017 is a LONG time ago...

Yes, i if it can be updated painfulness inside ruby-packer fork.

**Comment by ronaldtse** [comment]
> I think it will, you can set cert file for openssl gem inside the code. The question here is how much time we will spend on this in the end)

Perhaps the code can fetch SSL certificates from system?
